### ISSUE TITLE
UI functionality hindered due to merge

### ISSUE THREAD

**Issue by Sanjaeyss** [SKS2024SE/Unit_Conversion_2024#7]
Hey @SandhiyaS24 . Noticed that your recent merge to main has affected the UI capabilities of the application particularly the input fields, Especially in Dark mode. Please kindly have a look at it. I have attached screenshots of the issues below for your reference.

![image](https://github.com/user-attachments/assets/089c7fcd-61b8-440a-a15e-c0b1729776ab)

![image](https://github.com/user-attachments/assets/ff66784c-d437-4c8f-8c09-a102065971d6)

![image](https://github.com/user-attachments/assets/e1f68888-1ba1-4061-9b05-26670eb38173)

![image](https://github.com/user-attachments/assets/4924f452-f7f4-4752-b904-ae7a7106a306)

**Comment by SandhiyaS24** [comment]
The recent changes, particularly some updates from @Ks-Weasley, have impacted the UI, causing misalignments and inconsistencies. I've reverted the UI to the previous state and reapplied necessary updates.

Next steps:

Investigate and fix disrupted components.
Collaborate with @Ks-Weasley to align changes with design goals.
Test and refine for consistency.

Further updates will follow after the fixes.

**Comment by Sanjaeyss** [comment]
Ok @SandhiyaS24 . We will collaborate together on it. I would like to assist with it.

**Comment by Sanjaeyss** [comment]
@Ks-Weasley. Myself and @SandhiyaS24  worked on it. The Functionalities and UI issues have been rectified and are working now.
